var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/figures/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__04_x6_s._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0ul73e7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_01r1ky6.js")
R.c("server/chunks/ssr/[root-of-the-server]__0mmnj9t._.js")
R.c("server/chunks/ssr/[root-of-the-server]__09z7o2x._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0r_yofj._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0inhx6q._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0ghu-f7.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0cjv-23.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0lgvd_..js")
R.c("server/chunks/ssr/_next-internal_server_app_figures_page_actions_0h7u-oc.js")
R.m(27330)
module.exports=R.m(27330).exports
